name: hammock
version: 0.6.0
authors:
- Victor Savkin <vic.savkin@gmail.com>
- Till Wegmüller <toasterson@gmail.com>
- SWO Zivis <office@stiftungswo.ch>
homepage: https://github.com/Toasterson/hammock
description: AngularDart service for working with Rest APIs
dependencies:
  angular: '^4.0.0'
  http: "^0.11.3+16"
  di: any
dev_dependencies:
  test: "^0.12.32+1"
  angel_route: "^2.0.5"
environment:
  sdk: ">=1.4.0 <2.0.0"
