name: hammock
version: 0.7.0-alpha
authors:
- Victor Savkin <vic.savkin@gmail.com>
- Till Wegmüller <toasterson@gmail.com>
- SWO Zivis <office@stiftungswo.ch>
homepage: https://github.com/Toasterson/hammock
description: AngularDart service for working with Rest APIs
dependencies:
  angular: '^5.0.0'
  http: "^0.11.3+17"
dev_dependencies:
  test: "^1.3.0"
  angel_route: "^3.0.0"
environment:
  sdk: ">=2.0.0 <3.0.0"
