name: hammock_demo_app
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/hammock
dependencies:
  angular: "^5.0.0-alpha+7"
  angular_forms: "1.0.1-alpha+7"
  browser: any
  http_server: any
  hammock:
    path: '../'
dev_dependencies:
  build_runner: ^0.7.10+1
  build_test: ^0.10.0
  build_web_compilers: ^0.3.0
dependency_overrides:
  angular: "^5.0.0-alpha+7"
environment:
  sdk: ">=1.4.0 <2.0.0"
